export type GatewayProvider = 'openrouter' | 'anthropic' | 'deepseek' | 'openai' | 'custom';

export interface AgentStackConfig {
  architectModelId: string;
  architectModelName: string;
  editorModelId: string;
  editorModelName: string;
  autocompleteModelId?: string;
  autocompleteModelName?: string;
  provider: GatewayProvider;
  customBaseUrl?: string;
  enablePromptCaching: boolean;
}

export interface ExportedConfigFile {
  id: string;
  filename: string;
  title: string;
  language: 'yaml' | 'json' | 'markdown' | 'shell';
  content: string;
  instructions: string;
  runCommand: string;
}

export function sanitizeYamlScalar(val: string): string {
  const cleaned = val
    .split('')
    .filter((ch) => {
      const code = ch.charCodeAt(0);
      return code >= 32 && code !== 127;
    })
    .join('')
    .trim();
  if (/:\s|^[-?*&!|>'%@`#]/.test(cleaned)) {
    return JSON.stringify(cleaned);
  }
  return cleaned;
}

export function generateAiderConfig(config: AgentStackConfig): ExportedConfigFile {
  let mainModel = config.architectModelId;
  let editorModel = config.editorModelId;

  if (config.provider === 'openrouter') {
    if (!mainModel.startsWith('openrouter/')) mainModel = `openrouter/${mainModel}`;
    if (!editorModel.startsWith('openrouter/')) editorModel = `openrouter/${editorModel}`;
  }

  const lines = [
    `# Aider Configuration — Generated by Token-Max`,
    `# https://heretek-ai.github.io/Token-Max/#/exporter`,
    ``,
    `model: ${sanitizeYamlScalar(mainModel)}`,
    `editor-model: ${sanitizeYamlScalar(editorModel)}`,
    `cache-prompts: ${config.enablePromptCaching ? 'true' : 'false'}`,
    `stream: true`,
    `auto-commits: false`,
    `show-model-warnings: false`,
    `map-tokens: 2048`,
  ];

  if (config.provider === 'custom' && config.customBaseUrl) {
    lines.push(`openai-api-base: ${sanitizeYamlScalar(config.customBaseUrl)}`);
  }

  const content = lines.join('\n');

  let envInstruction = 'export OPENROUTER_API_KEY="sk-or-v1-..."';
  if (config.provider === 'anthropic') envInstruction = 'export ANTHROPIC_API_KEY="sk-ant-..."';
  if (config.provider === 'deepseek') envInstruction = 'export DEEPSEEK_API_KEY="sk-..."';
  if (config.provider === 'openai') envInstruction = 'export OPENAI_API_KEY="sk-..."';

  return {
    id: 'aider',
    filename: '.aider.conf.yml',
    title: 'Aider CLI',
    language: 'yaml',
    content,
    instructions: `Place this file in your project root or in ~/.aider.conf.yml to automatically route architect queries to ${config.architectModelName} and edits to ${config.editorModelName}.`,
    runCommand: `${envInstruction}\naider`,
  };
}

export function generateContinueConfig(config: AgentStackConfig): ExportedConfigFile {
  const providerKey = config.provider === 'openrouter' ? 'openrouter' : 'openai';
  const apiKeyVar = config.provider === 'openrouter' ? '${OPENROUTER_API_KEY}' : '${API_KEY}';

  const models: any[] = [
    {
      title: `Architect: ${config.architectModelName}`,
      provider: providerKey,
      model: config.architectModelId,
      apiKey: apiKeyVar,
    },
    {
      title: `Fast Editor: ${config.editorModelName}`,
      provider: providerKey,
      model: config.editorModelId,
      apiKey: apiKeyVar,
    },
  ];

  const continueObj: any = {
    $schema: 'https://continue.dev/schemas/config.json',
    models,
  };

  if (config.autocompleteModelId) {
    continueObj.tabAutocompleteModel = {
      title: `Autocomplete: ${config.autocompleteModelName || config.autocompleteModelId}`,
      provider: providerKey,
      model: config.autocompleteModelId,
      apiKey: apiKeyVar,
    };
  }

  if (config.provider === 'custom' && config.customBaseUrl) {
    continueObj.models.forEach((m: any) => {
      m.apiBase = config.customBaseUrl;
    });
    if (continueObj.tabAutocompleteModel) {
      continueObj.tabAutocompleteModel.apiBase = config.customBaseUrl;
    }
  }

  const content = JSON.stringify(continueObj, null, 2);

  return {
    id: 'continue',
    filename: 'config.json',
    title: 'Continue.dev',
    language: 'json',
    content,
    instructions: `Save this configuration in ~/.continue/config.json (or .continue/config.json in your workspace root) for VS Code or JetBrains.`,
    runCommand: `# Open Continue sidebar in VS Code / JetBrains\n# Models are instantly available in dropdown`,
  };
}

export function generateClineConfig(config: AgentStackConfig): ExportedConfigFile {
  const settings = {
    apiProvider: config.provider === 'openrouter' ? 'openrouter' : 'openai-native',
    apiModelId: config.architectModelId,
    openRouterBaseUrl: config.provider === 'custom' ? (config.customBaseUrl || 'https://openrouter.ai/api/v1') : 'https://openrouter.ai/api/v1',
    openRouterModelId: config.architectModelId,
    customModePrompts: {
      architect: {
        roleDefinition: `You are an expert system architect analyzing codebases and proposing high-level designs. Use ${config.architectModelName}.`,
        model: config.architectModelId,
      },
      code: {
        roleDefinition: `You are a fast software engineer making precision edits and running tests. Use ${config.editorModelName}.`,
        model: config.editorModelId,
      },
    },
    enablePromptCaching: config.enablePromptCaching,
  };

  const content = JSON.stringify(settings, null, 2);

  return {
    id: 'cline',
    filename: 'cline_custom_modes.json',
    title: 'Cline / Roo Code',
    language: 'json',
    content,
    instructions: `Import into Cline or Roo Code settings (or place in .roomodes / cline_custom_modes.json) to partition architect vs coder modes.`,
    runCommand: `# Set your API key in Cline extension settings or environment`,
  };
}

export function generateOpenCodeConfig(config: AgentStackConfig): ExportedConfigFile {
  const openCodeObj = {
    $schema: 'https://opencode.ai/config.schema.json',
    router: {
      primaryModel: config.architectModelId,
      fastModel: config.editorModelId,
      caching: config.enablePromptCaching,
      provider: config.provider,
      ...(config.customBaseUrl ? { baseUrl: config.customBaseUrl } : {}),
    },
  };

  const content = JSON.stringify(openCodeObj, null, 2);

  return {
    id: 'opencode',
    filename: 'opencode.json',
    title: 'OpenCode',
    language: 'json',
    content,
    instructions: `Save as opencode.json in your repository root to configure the OpenCode agent router.`,
    runCommand: `opencode start --config opencode.json`,
  };
}

export function generateCursorRules(config: AgentStackConfig): ExportedConfigFile {
  const content = [
    `# .cursorrules — Token-Max Optimized Agent Directives`,
    `# Generated: https://heretek-ai.github.io/Token-Max/#/exporter`,
    ``,
    `## Model Routing Guidelines`,
    `- For complex multi-file architectural planning and schema design, adopt the persona of ${config.architectModelName}.`,
    `- For rapid iterative code edits, unit test generation, and syntax linting, emulate ${config.editorModelName}.`,
    ``,
    `## Performance & Cache Optimization`,
    `- Minimize prompt churn: Keep system instructions static to maximize prompt-cache hits (${config.enablePromptCaching ? 'Enabled' : 'Disabled'}).`,
    `- Present concise unified diffs; avoid repeating unmodified file sections.`,
    `- Keep test runner invocations targeted to modified modules.`,
  ].join('\n');

  return {
    id: 'cursor',
    filename: '.cursorrules',
    title: 'Cursor (.cursorrules)',
    language: 'markdown',
    content,
    instructions: `Place in your repository root as .cursorrules to instruct Cursor Composer on role delegation and cache discipline.`,
    runCommand: `# Open project in Cursor IDE — rules apply automatically to Composer & Chat`,
  };
}

export function generateAllConfigs(config: AgentStackConfig): ExportedConfigFile[] {
  return [
    generateAiderConfig(config),
    generateContinueConfig(config),
    generateClineConfig(config),
    generateOpenCodeConfig(config),
    generateCursorRules(config),
  ];
}
