import type { NormalizedModel, CacheRate } from './types';
import {
  AGENT_REQUEST_INPUT_TOKENS,
  AGENT_REQUEST_OUTPUT_TOKENS,
  DEFAULT_CACHE_RATE,
} from './estimate-constants';
import { getEffectiveCacheMultiplier } from './pricing';

export type ReasoningEffort = 'off' | 'low' | 'medium' | 'high' | 'max';

export interface ReasoningEffortSpec {
  id: ReasoningEffort;
  label: string;
  tokens: number;
  description: string;
}

export const REASONING_EFFORT_SPECS: Record<ReasoningEffort, ReasoningEffortSpec> = {
  off: {
    id: 'off',
    label: 'Off (Direct Answer)',
    tokens: 0,
    description: 'Direct response without internal chain-of-thought or reasoning tokens',
  },
  low: {
    id: 'low',
    label: 'Low (~2,000 tokens)',
    tokens: 2000,
    description: 'Light sanity checking and quick planning before emitting code diffs',
  },
  medium: {
    id: 'medium',
    label: 'Medium (~8,000 tokens)',
    tokens: 8000,
    description: 'Standard multi-step code exploration, edge-case evaluation, and syntax verification',
  },
  high: {
    id: 'high',
    label: 'High (~24,000 tokens)',
    tokens: 24000,
    description: 'Deep architectural proofs, complex multi-file refactors, and algorithmic optimization',
  },
  max: {
    id: 'max',
    label: 'Max (~48,000 tokens)',
    tokens: 48000,
    description: 'Frontier reasoning limit for high-complexity codebases and intricate debugging',
  },
};

export interface ReasoningTurnCost {
  baseCost: number; // Cost of standard 20K input + 1K output tokens
  inputCost: number;
  outputCost: number;
  reasoningCost: number; // Hidden cost of thinking tokens billed at output rate
  totalCost: number;
  reasoningTokens: number;
  inflationMultiplier: number; // totalCost / baseCost
}

export interface MonthlyReasoningWorkload {
  turns: number;
  effort: ReasoningEffort;
  reasoningTokensPerTurn: number;
  totalTokensMillion: number;
  reasoningTokensMillion: number;
  monthlyBaseCost: number;
  monthlyReasoningCost: number;
  monthlyTotalCost: number;
  inflationMultiplier: number;
  monthlyReasoningTax: number; // monthlyTotalCost - monthlyBaseCost
}

export interface PlanAbsorptionPolicy {
  planId: string;
  planName: string;
  tierName: string;
  monthlyPrice: number | null;
  absorptionType: 'full-absorption' | 'quota-penalty' | 'pass-through';
  absorptionScore: number; // 0-100: higher = better shield for the developer against reasoning costs
  policySummary: string;
  evidenceQuote: string;
  url: string;
}

export const PLAN_ABSORPTION_POLICIES: PlanAbsorptionPolicy[] = [
  {
    planId: 'cursor-pro',
    planName: 'Cursor',
    tierName: 'Pro',
    monthlyPrice: 20,
    absorptionType: 'full-absorption',
    absorptionScore: 95,
    policySummary: 'Counts 1 fast request regardless of reasoning tokens. Absorbs up to $0.35/turn of compute.',
    evidenceQuote: 'Requests are deducted on a per-interaction basis. Reasoning tokens generated by Claude or o3 are absorbed within the fast request allowance.',
    url: 'https://cursor.com/docs/account/pricing',
  },
  {
    planId: 'cursor-ultra',
    planName: 'Cursor',
    tierName: 'Ultra',
    monthlyPrice: 400,
    absorptionType: 'full-absorption',
    absorptionScore: 98,
    policySummary: '20x fast pool with full absorption of extended thinking tokens.',
    evidenceQuote: '20x Pro pool with priority queue allocation across frontier reasoning models.',
    url: 'https://cursor.com/docs/account/pricing',
  },
  {
    planId: 'google-ai-pro',
    planName: 'Google Antigravity',
    tierName: 'Google AI Pro',
    monthlyPrice: 19.99,
    absorptionType: 'full-absorption',
    absorptionScore: 90,
    policySummary: 'Gemini 2.0/3.x Flash Thinking included in standard 5-hour refresh quotas.',
    evidenceQuote: 'Thinking models run against standard quota allocations. AI credit overage only triggered if opted-in.',
    url: 'https://antigravity.google/pricing',
  },
  {
    planId: 'claude-code-max5x',
    planName: 'Claude Code',
    tierName: 'Max5x',
    monthlyPrice: 100,
    absorptionType: 'quota-penalty',
    absorptionScore: 75,
    policySummary: '5x pool cushions against thinking burnout, but Fable Thinking burns weekly quota at 1.5x speed.',
    evidenceQuote: 'Claude Fable draws weekly limits at 50% extra burn rate; 5-hour rolling pool absorbs tokens up to window ceiling.',
    url: 'https://claude.com/pricing',
  },
  {
    planId: 'claude-code-pro',
    planName: 'Claude Code',
    tierName: 'Pro',
    monthlyPrice: 20,
    absorptionType: 'quota-penalty',
    absorptionScore: 65,
    policySummary: 'Absorbs thinking into 5-hour pool, but heavy reasoning exhausts rolling quota in under 1 hour.',
    evidenceQuote: 'Shared 5-hour rolling session limit. High reasoning token generation drains the dynamic token window faster.',
    url: 'https://claude.com/pricing',
  },
  {
    planId: 'deepseek-api-r1',
    planName: 'DeepSeek API',
    tierName: 'DeepSeek-R1 (PAYG)',
    monthlyPrice: null,
    absorptionType: 'pass-through',
    absorptionScore: 85,
    policySummary: 'Direct pass-through billing, but ultra-low pricing ($2.19/M output) keeps reasoning affordable.',
    evidenceQuote: 'Reasoning tokens are billed at standard output token rates: ¥16/M peak, ¥8/M off-peak (~$1.10–$2.19/M USD).',
    url: 'https://api-docs.deepseek.com/quick_start/pricing',
  },
  {
    planId: 'opencode-zen',
    planName: 'OpenCode',
    tierName: 'Zen',
    monthlyPrice: 10,
    absorptionType: 'pass-through',
    absorptionScore: 60,
    policySummary: 'Pass-through API rates without markup; reasoning tokens drain wallet balance directly.',
    evidenceQuote: 'Direct provider pass-through. Zero token markup; users pay exact provider per-token output pricing.',
    url: 'https://opencode.ai/pricing',
  },
  {
    planId: 'openai-api-o3',
    planName: 'OpenAI API',
    tierName: 'o3 / o4-mini (PAYG)',
    monthlyPrice: null,
    absorptionType: 'pass-through',
    absorptionScore: 35,
    policySummary: 'Unshielded pass-through: Reasoning tokens are fully billed as output tokens at $10.00–$15.00/M.',
    evidenceQuote: 'Reasoning tokens are billed as output tokens. For high-effort queries, total output tokens can exceed 25,000.',
    url: 'https://platform.openai.com/docs/guides/reasoning',
  },
  {
    planId: 'anthropic-api-thinking',
    planName: 'Anthropic API',
    tierName: 'Claude 3.7 Thinking (PAYG)',
    monthlyPrice: null,
    absorptionType: 'pass-through',
    absorptionScore: 30,
    policySummary: 'Unshielded pass-through: Thinking budget is billed at full $15.00/M output token rates.',
    evidenceQuote: 'Thinking tokens are billed as output tokens at standard model rates ($15/M on Sonnet, $75/M on Opus).',
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking',
  },
];

/**
 * Computes single-turn cost breakdown including base input, visible output, and hidden reasoning tokens.
 */
export function calculateReasoningCost(
  model: NormalizedModel,
  cacheRate: CacheRate = DEFAULT_CACHE_RATE,
  effort: ReasoningEffort = 'medium'
): ReasoningTurnCost {
  const effortSpec = REASONING_EFFORT_SPECS[effort];
  const reasoningTokens = effortSpec.tokens;

  const inPrice = model.pricing.input || model.blendedCost * 0.75;
  const outPrice = model.pricing.output || model.blendedCost * 1.75;
  const cacheMult = getEffectiveCacheMultiplier(model);

  // Fresh vs cached input tokens
  const freshInputTokens = AGENT_REQUEST_INPUT_TOKENS * (1 - cacheRate);
  const cachedInputTokens = AGENT_REQUEST_INPUT_TOKENS * cacheRate;

  const inputCost = (freshInputTokens * inPrice / 1e6) + (cachedInputTokens * inPrice * cacheMult / 1e6);
  const outputCost = AGENT_REQUEST_OUTPUT_TOKENS * outPrice / 1e6;
  const baseCost = inputCost + outputCost;

  // Reasoning tokens are billed at the model's reasoning rate if available, else at standard output rate
  const reasoningRate = model.pricing.reasoning ?? outPrice;
  const reasoningCost = (reasoningTokens * reasoningRate) / 1e6;
  const totalCost = baseCost + reasoningCost;
  const inflationMultiplier = baseCost > 0 ? totalCost / baseCost : 1.0;

  return {
    baseCost,
    inputCost,
    outputCost,
    reasoningCost,
    totalCost,
    reasoningTokens,
    inflationMultiplier: Number(inflationMultiplier.toFixed(2)),
  };
}

/**
 * Computes monthly aggregated workload spend with reasoning tokens.
 */
export function calculateMonthlyReasoningWorkload(
  model: NormalizedModel,
  turns: number,
  cacheRate: CacheRate = DEFAULT_CACHE_RATE,
  effort: ReasoningEffort = 'medium'
): MonthlyReasoningWorkload {
  const turn = calculateReasoningCost(model, cacheRate, effort);
  const effortSpec = REASONING_EFFORT_SPECS[effort];

  const totalTokensPerTurn = AGENT_REQUEST_INPUT_TOKENS + AGENT_REQUEST_OUTPUT_TOKENS + turn.reasoningTokens;
  const totalTokensMillion = (totalTokensPerTurn * turns) / 1e6;
  const reasoningTokensMillion = (turn.reasoningTokens * turns) / 1e6;

  const monthlyBaseCost = turn.baseCost * turns;
  const monthlyReasoningCost = turn.reasoningCost * turns;
  const monthlyTotalCost = turn.totalCost * turns;
  const monthlyReasoningTax = monthlyTotalCost - monthlyBaseCost;

  return {
    turns,
    effort,
    reasoningTokensPerTurn: effortSpec.tokens,
    totalTokensMillion: Number(totalTokensMillion.toFixed(2)),
    reasoningTokensMillion: Number(reasoningTokensMillion.toFixed(2)),
    monthlyBaseCost,
    monthlyReasoningCost,
    monthlyTotalCost,
    inflationMultiplier: turn.inflationMultiplier,
    monthlyReasoningTax,
  };
}
